import"./assets/styles-JE8YjOlG.js";import{a as r}from"./assets/vendor-N5iQpiFS.js";const l="https://dummyjson.com",n=12,d="modal--is-open",s={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCT:"/products"};r.defaults.baseURL=l;async function u(){const{data:t}=await r(`${s.CATEGORIES}`);return t}async function p(t){const e={params:{skip:(t-1)*n,limit:n}},{data:o}=await r(s.PRODUCTS,e);return o}async function m(t){const{data:e}=await r(`${s.PRODUCTS}/${t}`);return e}const c={body:document.querySelector("body"),categoryList:document.querySelector(".categories"),productList:document.querySelector("ul.products"),modal:document.querySelector("div.modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),backdrop:document.querySelector(".modal__backdrop")};function y(t){const e=t.map(o=>`<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>`).join("");c.categoryList.innerHTML=e}function _(t){const e=t.products.map(o=>`<li class="products__item" data-id="${o.id}">
    <img class="products__image" src="${o.thumbnail}" alt="product image"/>
    <p class="products__title">${o.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: </span>${o.brand}</p>
    <p class="products__category">Category: ${o.category}</p>
    <p class="products__price">Price: $${o.price}</p>
 </li>`).join("");c.productList.insertAdjacentHTML("beforeend",e)}function g(){c.body.style.overflow="hidden",c.modal.classList.add(d),document.addEventListener("keydown",i)}function a(){c.body.style.overflow="",c.modal.classList.remove(d),document.removeEventListener("keydown",i)}function i(t){t.key==="Escape"&&a()}async function f(){try{const t=await u();y(["All",...t]);const e=document.querySelector(".categories__btn");e&&e.classList.add("categories__btn--active")}catch(t){console.log(t)}}async function b(t){try{const e=await p(t);_(e)}catch(e){console.log(e)}}async function L(t){try{const e=await m(t);renderProduct(e),g()}catch(e){console.log(e)}}f();b(1);c.categoryList.addEventListener("click",t=>{t.target.classList("categories__btn")});c.productList.addEventListener("click",t=>{if(t.target===t.currentTarget)return;const e=t.target.closest(".products__item").dataset.id;L(e)});c.modal.addEventListener("click",t=>{t.target===t.currentTarget&&a()});c.modalCloseBtn.addEventListener("click",t=>{a()});
//# sourceMappingURL=index.js.map
